//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample_v14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public System.DateTime release_date { get; set; }
    }
}
